# Generated by Django 2.1.5 on 2019-01-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_order_ordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_img',
            field=models.ImageField(upload_to='buyer/images'),
        ),
    ]
