# Generated by Django 2.1.5 on 2019-01-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_auto_20190118_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
